name 'provision'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures provision'
long_description 'Installs/Configures provision'
version '0.1.0'
