name 'cs-influx'
maintainer 'Andrew DuFour'
maintainer_email 'andy.k.dufour@gmail.com'
license 'all_rights'
description 'Installs/Configures InfluxDB and Telegraf'
long_description 'Installs/Configures InfluxDB and Telegraf'
version '0.1.0'

depends 'apt'
depends 'yum'
