---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 8080, host: 8080}]

provisioner:
  name: policyfile_zero

platforms:
  - name: ubuntu-14.04
    driver_config:
      network:
      - ["private_network", {ip: "192.168.56.50"}]
      customize:
        cpus: 1
        memory: 2048

suites:
  - name: default
    data_bags_path: "test/integration/data_bags"
    attributes:
