---
driver:
  name: vagrant

provisioner:
  name: chef_zero
#  require_chef_omnibus: 12.7.0

platforms:
  - name: ubuntu-14.04
    driver_config:
      network:
      - ["private_network", {ip: "192.168.56.50"}]
      customize:
        cpus: 1
        memory: 2048

suites:
  - name: monitoring
    run_list:
    - recipe[cs-monitor::default]
    data_bags_path: "test/integration/data_bags"
    attributes:
  - name: statsd
    run_list:
    - recipe[cs-monitor::statsd]
