name 'chef-server-monitoring'
maintainer 'Andrew Dufour'
maintainer_email 'adufour@chef.io'
license 'all_rights'
description 'Installs/Configures chef-server-monitoring'
long_description 'Installs/Configures chef-server-monitoring'
version '0.1.0'
source_url       'https://github.com/andy-dufour/chef-server-monitoring/'
issues_url       'https://github.com/andy-dufour/chef-server-monitoring/issues'

depends 'cs-monitor'
depends 'hostsfile'
depends 'chef-provisioning-vagrant-helper'
depends 'chef-provisioning-aws-helper'
