name 'cs-statsd'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures cs-statsd'
long_description 'Installs/Configures cs-statsd'
version '0.1.0'
